### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Duy-Thanh** [Duy-Thanh/Pinball-On-Android#1]
Here is the upcoming changes I will make for this repository:

- [ ] Sync with fexed's repository
- [ ] Update SDL and SDL_mixer library to latest version
- [ ] Sync SpaceCadetPinball C++ sources code with k4zmu2a's repository
- [ ] Update to work on newer Android Studio version, newer Gradle version and newer Android version
- [ ] Re-write some parts
- [ ] Add iOS as target supported platform

I will update this TODO list regularly, so please follow!
